import type { NextPage } from "next";
import { trpc } from "../utils/trpc";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Footer from "../../components/footer";

import { heroBtn } from "../../components/buttons/buttons.component.jsx";
import styles from "./index.module.scss";

const Home: NextPage = () => {
  const { data } = trpc.example.hello.useQuery({ text: "from tRPC" });

  let slidecount = 0;

  // const test = { opacity = 0 };

  return (
    <>
      <Head>
        <title>Mom's Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homeContainer}>
        <div className={styles.welcome__container}>
          <div className={styles.welcome__textBox}>
            <h1>TESTTTINNNNNGGG!!!</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatem, ab nisi eos mollitia autem consequatur quod suscipit
              inventore porro officia in dicta molestiae voluptatum. Dicta
              similique tempora vel? Asperiores, et? Lorem ipsum dolor sit amet
              consectetur adipisicing elit.
            </p>
            <button>
              <a href={""} target="_blank" rel="noreferrer">
                Latest Blog →
              </a>
            </button>
          </div>
          <div className={styles.welcome__slider}>
            {/* <img src="slide1.jpg" alt="" className={styles.welcome__slide} /> */}
            <img
              src="slide2.jpg"
              alt=""
              className={styles.welcome__slide}
              // ref={test}
            />
            {/* <img src="slide3.jpg" alt="" className={styles.welcome__slide} /> */}
          </div>
        </div>
        <div className={styles.marketingContainer}>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum,
            optio quod, deserunt laudantium iste tenetur et voluptas, vel totam
            nobis quisquam! Alias autem delectus minus, sapiente elit. Eum ipsa
            modi veniam magni corrupti consequatur soluta praesentium molestiae
            omnis ratione nesciunt adipisci dicta hic est corporis sapiente,
            veritatis fugiat eos?
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum,
            optio quod, deserunt laudantium iste tenetur et voluptas, vel totam
            nobis quisquam! Alias autem delectus minus, sapiente id quos quae
            voluptatem. Lorem ipsum dolor sit, amet consectetur adipisicing
            elit. Eum ipsa modi veniam magni corrupti consequatur soluta
            praesentium molestiae omnis ratione nesciunt adipisci dicta hic est
            corporis sapiente, veritatis fugiat eos?
          </p>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

  const { data: sessionData } = useSession();

  return (
    <div className={styles.authShowcase}>
      {sessionData && <p>Logged in as {sessionData?.user?.name}</p>}
      {secretMessage && <p>{secretMessage}</p>}
      <button
        className={styles.signInButton}
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
