import type { NextPage } from "next";
import { trpc } from "../utils/trpc";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Footer from "../../components/footer";
import HeroSlider from "../../components/heroSlider";
import Marketing from "../../components/marketing";

import styles from "./index.module.scss";
import { useInView } from "react-intersection-observer";

const Home: NextPage = () => {
  const { data } = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Mom's Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className={styles.homeContainer}>
        <div className={styles.welcome__container}>
          <div className={styles.absoluteTextBox}>
            <div className={styles.welcome__textBox}>
              <h1 className={styles.company_name}>Cascade Counseling</h1>
              <p>
                <em className={styles.company_name_secondLine}>
                  For Personal Empowerment
                </em>
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Voluptatem, ab nisi eos mollitia autem consequatur quod suscipit
                inventore porro officia in dicta molestiae voluptatum. Dicta
              </p>
              <button>
                <a href={""} target="_blank" rel="noreferrer">
                  Latest Blog →
                </a>
              </button>
            </div>
          </div>
          <HeroSlider />
        </div>
        <Marketing />
        <Footer />
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

  const { data: sessionData } = useSession();

  return (
    <div className={styles.authShowcase}>
      {sessionData && <p>Logged in as {sessionData?.user?.name}</p>}
      {secretMessage && <p>{secretMessage}</p>}
      <button
        className={styles.signInButton}
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
